name: reusable wf 2

# Controls when the workflow will run
on:
  workflow_call:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: echo Hello, 2
